name: Daily YNAB Google Sheets Update

on:
  schedule:
    # 8 AM Mexico City time = 14:00 UTC (UTC-6)
    - cron: '0 14 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-ynab-sheets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create service account JSON file
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > service-account.json
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        
    - name: Run YNAB Google Sheets update
      run: |
        python3 update_gsheets.py --testing
      env:
        GSHEETS_SERVICE_ACCOUNT_FILE: ./service-account.json
        GSHEETS_SPREADSHEET_ID: ${{ secrets.GSHEETS_SPREADSHEET_ID }}
        YNAB_ACCESS_TOKEN: ${{ secrets.YNAB_ACCESS_TOKEN }}
        MAIN_BUDGET_ID: ${{ secrets.MAIN_BUDGET_ID }}
        SECONDARY_BUDGET_ID: ${{ secrets.SECONDARY_BUDGET_ID }}
        
    - name: Clean up service account file
      run: rm -f service-account.json
      if: always()  # Clean up even if the previous step fails
