name: Weekly YNAB Alerts

on:
  schedule:
    # Every Friday at 14:10 UTC (8:10 AM Mexico City, UTC-6)
    - cron: "10 14 * * 5"
  workflow_dispatch: # Allows manual triggering

jobs:
  weekly-ynab-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account JSON file
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > service-account.json
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}

      - name: Run YNAB Alerts
        run: |
          python3 ynab_alerts.py
        env:
          GSHEETS_SERVICE_ACCOUNT_FILE: ./service-account.json
          GSHEETS_SPREADSHEET_ID: ${{ secrets.GSHEETS_SPREADSHEET_ID }}
          YNAB_ACCESS_TOKEN: ${{ secrets.YNAB_ACCESS_TOKEN }}
          MAIN_BUDGET_ID: ${{ secrets.MAIN_BUDGET_ID }}
          SECONDARY_BUDGET_ID: ${{ secrets.SECONDARY_BUDGET_ID }}
          YNAB_ALERT_THRESHOLD_PERCENT: 25
          YNAB_ALERT_RECIPIENTS: ${{ secrets.YNAB_ALERT_RECIPIENTS }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

      - name: Clean up service account file
        run: rm -f service-account.json
        if: always()
